import{a as f,S as d,i as l}from"./assets/vendor-DirGshhi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const m="https://pixabay.com/api/",p="56128915-3f9b657c3018140957932d29d";function y(n){return f.get(m,{params:{key:p,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data.hits).catch(t=>{console.log(t)})}let c=document.querySelector(".gallery"),u=document.querySelector(".js-loader");function h(){c.innerHTML=""}function g(){u.classList.add("loader")}function i(){u.classList.remove("loader")}function b(n){const t=n.map(r=>`<li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
         <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" title="${r.name}" />
        </a>
        <div class="info">
         <p class="info-item"> <b>Likes</b> ${r.likes} </p>
         <p class="info-item"> <b>Views</b> ${r.views} </p>
         <p class="info-item"> <b>Comments</b> ${r.comments} </p>
         <p class="info-item"> <b>Downloads</b> ${r.downloads} </p>
        </div>`).join("");c.insertAdjacentHTML("beforeend",t),new d(".gallery a",{captionsDelay:250,captionsData:"title"}).refresh()}l.settings({timeout:1e4,resetOnHover:!0,icon:"material-icons",transitionIn:"flipInX",transitionOut:"flipOutX"});let L=document.querySelector(".form");L.addEventListener("submit",w);function w(n){n.preventDefault(),h(),g();const t=n.currentTarget.elements["search-text"].value.trim();Promise.all([y(t),new Promise(s=>setTimeout(s,1e3))]).then(([s])=>{if(s.length==0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft"}),i();return}b(s),i()}).catch(s=>{i(),console.log(s)})}
//# sourceMappingURL=index.js.map
